<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet exclude-result-prefixes="#all" version="2.0"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

	<xsl:template as="empty-sequence()" match="context-element-for-my-template" mode="with-error"
		name="my-template-with-error">
		<xsl:sequence
			select="
				error(
				xs:QName('error-code-of-my-template'),
				'error description of my template',
				('error', 'object', 'of', 'my', 'template')
				)"
		 />
	</xsl:template>

	<xsl:template as="xs:string" match="context-element-for-my-template" mode="without-error"
		name="my-template-without-error">
		<xsl:sequence select="'string generated by my template'" />
	</xsl:template>

</xsl:stylesheet>
