titleOnly: true

#
# Sync these types and scopes with CONTRIBUTING.md
#

types:
  - feat
  - fix
  - test
  - ci
  - docs
  - perf
  - refactor
  - style
  - build

scopes:
  - xslt
  - xquery
  - schematron
  - oxygen
  - basex
  - deps
  - report
  - xproc
  - schema
