<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet exclude-result-prefixes="#all" version="2.0"
	xmlns:serializer="x-urn:xspec:test:end-to-end:processor:serializer"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

	<!--
		This stylesheet module helps serialize the test result XML.
	-->

	<!--
		Set of serialization parameters
			The parameters must be in sync with
				XQuery: "declare option output:*" generated by XSPEC_HOME/src/compiler/generate-query-tests.xsl
				XSLT:   <output name="x:report"> generated by XSPEC_HOME/src/compiler/generate-xspec-tests.xsl
	-->
	<xsl:output indent="yes" method="xml" name="serializer:output" />
</xsl:stylesheet>
