<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet exclude-result-prefixes="#all" version="3.0"
	xmlns:serializer="x-urn:xspec:test:end-to-end:processor:serializer"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

	<!--
		This stylesheet module helps serialize the test result XML.
	-->

	<!--
		Set of serialization parameters
			The parameters must be in sync with
				XQuery: "declare option output:*" generated by XSPEC_HOME/src/compiler/compile-xquery-tests.xsl
				XSLT:   <xsl:result-document> generated by XSPEC_HOME/src/compiler/compile-xslt-tests.xsl
	-->
	<xsl:output name="serializer:output" 
		parameter-document="../../../../src/common/xml-report-serialization-parameters.xml"/>
</xsl:stylesheet>
