name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: test/ci/run-commitlint.sh
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
