name: Test

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    env:
      XSPEC_TEST_ENV: ${{ matrix.env }}

    strategy:
      fail-fast: false

      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ 8, 11 ]
        env: [ saxon-10, saxon-9-9, saxon-9-8, oxygen, saxon-9-7 ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Install Bats for Linux
        if: runner.os == 'Linux'
        run: sudo npm install -g bats

      - name: Run tests for *nix
        if: runner.os != 'Windows'
        run: >
          source test/ci/install-deps.sh
          && test/ci/print-env.sh
          && test/ci/run-core-tests.sh
          && test/ci/maven-package.sh -q
          && test/ci/compile-java.sh -silent
          && test/ci/last-git-status.sh

      - name: Run tests for Windows
        if: runner.os == 'Windows'
        shell: cmd
        run: >
          call test\ci\install-deps.cmd
          && call test\ci\print-env.cmd
          && call test\ci\run-core-tests.cmd
          && call test\ci\maven-package.cmd -q
          && call test\ci\compile-java.cmd -silent
          && call test\ci\last-git-status.cmd

